### ISSUE TITLE
hangs with simple 7 point hull

### ISSUE THREAD

**Issue by vird** [maurizzzio/quickhull3d#2]
[ [ 104, 216, 53 ],
      [ 104, 217, 52 ],
      [ 105, 216, 52 ],
      [ 88, 187, 43 ],
      [ 89, 187, 44 ],
      [ 89, 188, 43 ],
      [ 90, 187, 43 ] ]

node -v

    v0.10.38

convex-hull module calcs ok

    [ [ 0, 1, 3 ],
      [ 1, 0, 2 ],
      [ 4, 0, 3 ],
      [ 0, 4, 2 ],
      [ 1, 5, 3 ],
      [ 5, 1, 2 ],
      [ 6, 4, 3 ],
      [ 5, 6, 3 ],
      [ 2, 4, 6 ],
      [ 5, 2, 6 ] ]

version 1.1.1

**Comment by maurizzzio** [comment]
Thanks for the report! checking...

**Comment by maurizzzio** [comment]
It should be good now, there was a problem with the face merging algorithm that made a the edges of a face which was not in the hull to be constantly iterated trying to find a "twin" edge

v1.2.0 (refs 9ac4bcfef6684c1a074b69f2a90624a2fd3ac9d2)
