### ISSUE TITLE
AssertionError: attempting to join destroyed faces

### ISSUE THREAD

**Issue by vird** [maurizzzio/quickhull3d#3]
version 1.2.0
https://gist.github.com/vird/504480852c61b1983ca8
convex-hull module result included
sorry, not a minimal report

**Comment by maurizzzio** [comment]
thanks again for the report! I think I'm gonna rewrite quickhull over the weekend as an exercise to learn es6 and also to find the bug! sorry if v1.2.0 didn't fix the problem completely

**Comment by maurizzzio** [comment]
sorry for the late response, I've been quite busy but finally I rewrote this project in ES6 (5cd445d84eda846c43b68652ef65c482564e9e71)

Should be fixed on v2.0.0
