### ISSUE TITLE
Gives different set of faces to Matlab convhulln

### ISSUE THREAD

**Issue by DastardlyMut** [maurizzzio/quickhull3d#4]
Hello! 

First of all, thank you for making this code accessible.

I've been transcribing some MATlab code into Javascript and need to find the triangle faces making up the convex hull of a set of vertices (in 3D coordinates). The MATlab code uses the convhulln function. This convhulln function also makes use of the qhull as implemented in http://www.qhull.org/. http://www.mathworks.com/help/matlab/ref/convhulln.html

This library doesn't seem to be outputting the same triangle faces to that of convulln and I'm not quite sure why. There are some faces that are similar but in general, most are not. The only similarity between convulln and quickhull-3d is they output the same number of faces that make up the convex hull (but these faces are not the same in general)

Any light you could shed on this would be greatly appreciated. 

Here are the vertices I'm using and the results of both MATlab's convhulln and quickhull3d. Please note I've used a sorting algorithm to sort them in the from first vertices to last. This should not effect the actual triangle faces since I sorted them in exactly the same way in both the MATlab and JS code.
**EDIT:** The sorting function I implemented initially was incorrect. Have changed it to the correct one but still get different output (likely to do with the triangulation process implemented after convex hull is found)

```
vertices = [ 
  [ 0.9510565162951535, -0.3090169943749474, 0 ],
  [ 0.5877852522924731, -0.8090169943749475, 0 ],
  [ 6.123233995736766e-17, -1, 0 ],
  [ -0.5591929034707466, 0.8290375725550418, 0 ],
  [ -0.9510565162951535, -0.3090169943749475, 0 ],
  [ -0.9510565162951536, 0.3090169943749473, 0 ],
  [ -0.5877852522924732, 0.8090169943749473, 0 ],
  [ -1.8369701987210297e-16, 1, 0 ],
  [ 0.5877852522924729, 0.8090169943749476, 0 ],
  [ 0.9510565162951535, 0.3090169943749476, 0 ],
  [ 0.984807753012208, 0, -0.17364817766693033 ],
  [ 0.30432233187297814, -0.9366078308002486, -0.17364817766693033 ],
  [ -0.796726208379082, -0.5788554735638644, -0.17364817766693033 ],
  [ -0.7967262083790821, 0.5788554735638641, -0.17364817766693033 ],
  [ 0.3043223318729779, 0.9366078308002487, -0.17364817766693033 ],
  [ 0.5000000000000001, -0.5, 0.7071067811865475 ],
  [ -0.5, -0.5000000000000001, 0.7071067811865475 ],
  [ -0.5000000000000001, 0.5, 0.7071067811865475 ],
  [ 0.4999999999999999, 0.5000000000000001, 0.7071067811865475 ],
  [ 6.123233995736766e-17, 0, 1 ] 
]
```

triangles from quickhull3d:
dim = 36x3
```
trianglesqh = [ 
  [ 0, 10, 11 ],
  [ 1, 0, 11 ],
  [ 1, 15, 0 ],
  [ 2, 1, 11 ],
  [ 2, 11, 12 ],
  [ 2, 15, 1 ],
  [ 5, 13, 6 ],
  [ 5, 17, 4 ],
  [ 6, 13, 3 ],
  [ 7, 14, 8 ],
  [ 7, 17, 3 ],
  [ 7, 18, 17 ],
  [ 9, 10, 0 ],
  [ 9, 18, 8 ],
  [ 10, 9, 8 ],
  [ 10, 14, 12 ],
  [ 11, 10, 12 ],
  [ 12, 13, 4 ],
  [ 13, 5, 4 ],
  [ 13, 14, 3 ],
  [ 14, 7, 3 ],
  [ 14, 10, 8 ],
  [ 14, 13, 12 ],
  [ 15, 2, 16 ],
  [ 15, 18, 0 ],
  [ 15, 19, 18 ],
  [ 16, 2, 12 ],
  [ 16, 12, 4 ],
  [ 17, 5, 6 ],
  [ 17, 6, 3 ],
  [ 17, 16, 4 ],
  [ 17, 19, 16 ],
  [ 18, 7, 8 ],
  [ 18, 9, 0 ],
  [ 18, 19, 17 ],
  [ 19, 15, 16 ] 
]
```

triangles from MATlab:
dim = 36x3
```
trianglesm = [ 
  [ 0, 1, 11 ],
  [ 0, 9, 18 ],
  [ 0, 10, 9 ],
  [ 0, 11, 10 ],
  [ 0, 15, 1 ],
  [ 0, 18, 15 ],
  [ 1, 2, 11 ],
  [ 1, 18, 2 ],
  [ 2, 3, 11 ],
  [ 2, 15, 16 ],
  [ 2, 16, 3 ],
  [ 3, 4, 12 ],
  [ 3, 12, 11 ],
  [ 3, 16, 4 ],
  [ 4, 5, 12 ],
  [ 4, 17, 5 ],
  [ 5, 8, 13 ],
  [ 5, 13, 12 ],
  [ 5, 16, 17 ],
  [ 5, 17, 6 ],
  [ 6, 7, 14 ],
  [ 6, 14, 13 ],
  [ 6, 17, 7 ],
  [ 7, 8, 14 ],
  [ 7, 17, 18 ],
  [ 7, 18, 8 ],
  [ 8, 9, 10 ],
  [ 8, 10, 14 ],
  [ 8, 18, 9 ],
  [ 10, 11, 14 ],
  [ 11, 12, 13 ],
  [ 11, 13, 14 ],
  [ 15, 18, 19 ],
  [ 15, 19, 16 ],
  [ 16, 19, 17 ],
  [ 17, 19, 18 ]
 ]
```

And here are images of the convex hull (done in matlab)

Matlab Hull
![hull](https://cloud.githubusercontent.com/assets/13471797/15514169/0fd20afe-21e8-11e6-91c7-da069e9bf18e.PNG)

Quickhull3d Hull
![hullwrong](https://cloud.githubusercontent.com/assets/13471797/15517589/d7fa7fba-21f8-11e6-9c05-c576a899bfb2.PNG)

Holes in the convex hull.

**Comment by maurizzzio** [comment]
The sorting algorithm you used is not working correctly for the output of quickhull3d, remember that if a face `[a, b, c]` is given all the following are equivalent

- `[a, b, c]`
- `[b, c, a]`
- `[c, a, b]`

If your objective is to have the lowest index first for a given face then you could implement the sorting like this

[make each face have its lowest index first](http://esnextb.in/?gist=1a54c71953a74c372d43fd7f55194282)

```plain
[ [ 0, 1, 11 ],
  [ 0, 9, 18 ],
  [ 0, 10, 9 ],
  [ 0, 11, 10 ],
  [ 0, 15, 1 ],
  [ 0, 18, 15 ],
  [ 1, 2, 11 ],
  [ 1, 15, 2 ],
  [ 2, 12, 11 ],
  [ 2, 15, 16 ],
  [ 2, 16, 12 ],
  [ 3, 6, 17 ],
  [ 3, 7, 14 ],
  [ 3, 13, 6 ],
  [ 3, 14, 13 ],
  [ 3, 17, 7 ],
  [ 4, 5, 13 ],
  [ 4, 12, 16 ],
  [ 4, 13, 12 ],
  [ 4, 16, 17 ],
  [ 4, 17, 5 ],
  [ 5, 6, 13 ],
  [ 5, 17, 6 ],
  [ 7, 8, 14 ],
  [ 7, 17, 18 ],
  [ 7, 18, 8 ],
  [ 8, 9, 10 ],
  [ 8, 10, 14 ],
  [ 8, 18, 9 ],
  [ 10, 11, 12 ],
  [ 10, 12, 14 ],
  [ 12, 13, 14 ],
  [ 15, 18, 19 ],
  [ 15, 19, 16 ],
  [ 16, 19, 17 ],
  [ 17, 19, 18 ] ]
```

Now the output looks like a lot like the output from matlab however it's still different, a robust quickhull implementation will join faces if they seem to be collinear (check out the examples in [this awesome presentation](http://box2d.org/files/GDC2014/DirkGregorius_ImplementingQuickHull.pdf) to understand the reasoning behind this merge), after successive face merges we might have faces with n-vertices (n > 3), after the quickhull algorithm has finished the next step is to triangulate these faces with n-vertices (n > 3), I implemented the triangulation as follows

- let `i` be a vertex of a face with `n` vertices, create `n - 2` faces with vertices 
 - `[i, j + 1, j + 2]`
 - `[i, j + 2, j + 3]`
 - ...
 - `[i, n - 2, n - 1]`
 - `[i, n - 1, n]`

I guess that this is the place where the vertices differ since matlab might be using a different algorithm for the triangulation

**Comment by DastardlyMut** [comment]
Thank you so much for your fast response! I indeed needed my sort algorithm to do that but went about it by inverting the triangle faces vertices then doing a circular shift to get the smallest entry first (inspired by matlab code). Thanks for pointing this out.

I agree that this is likely the case then. I'm assuming the Matlab code uses the Delaunay Triangulation algorithm instead of the one you've implemented.

Thanks for the link to that great presentation. I have updated the pictures with the plot of the output quickhull3d as it stands with the sorting function corrected.

**Comment by maurizzzio** [comment]
Inverting the vertices of a face will actually make the face look in the opposite direction, if you still have doubts about the algorithm feel free to reopen this issue or open a new one

**Comment by DastardlyMut** [comment]
Yeah, I thought as much.. Must have been my circular shift function that was not working properly..
All these concepts are still very new to me so I want to run through your code properly, read up some more and see how I can modify to get the result I need. This being said, surely the convex hull for the set of vertices I gave is not correct as there are definate holes?

I will let you know how it goes. Thanks so much for your input!
